// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gacmbxwwyiwlxbwaqubb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhY21ieHd3eWl3bHhid2FxdWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzU3MTEsImV4cCI6MjA3MzY1MTcxMX0.KZOgSveel5qVwvY1UJIBK7y_BKkGvh8qahwVFtrbLp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});