// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwmsoplazqvlqtloxxlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bXNvcGxhenF2bHF0bG94eGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTExMTUsImV4cCI6MjA3NzE4NzExNX0.fLr-0kGxysfXSIL31oSw1XrjzEvFfS0qhuWTGCBPzLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});